apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcbds-deployment
  labels:
    app: mcbds
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mcbds
  template:
    metadata:
      labels:
        app: mcbds
    spec:
      containers:
      - name: mcbds
        image: starchx/minecraft-bds:v1.14
        imagePullPolicy: Always
        env:
        - name: default_level
          value: KCHolidayLuckyBlock
        ports:
        - containerPort: 19132
          protocol: UDP
        resources:
          requests:
            memory: "3072Mi"
            cpu: "1000m"
          limits:
            memory: "3072Mi"
            cpu: "2000m"
    
