apiVersion: v1
kind: Service
metadata:
  name: mcbds-service-888
  labels:
    app: mcbds-888
spec:
  type: NodePort
  selector:
    app: mcbds-888
  ports:
  - protocol: UDP
    port: 19132
    nodePort: 31888

---

apiVersion: v1
kind: Service
metadata:
  name: mcbds-service-777
  labels:
    app: mcbds-777
spec:
  type: NodePort
  selector:
    app: mcbds-777
  ports:
  - protocol: UDP
    port: 19132
    nodePort: 31777

---

apiVersion: v1
kind: Service
metadata:
  name: mcbds-service-999
  labels:
    app: mcbds-999
spec:
  type: NodePort
  selector:
    app: mcbds-999
  ports:
  - protocol: UDP
    port: 19132
    nodePort: 31999
